name: Initial Setup

on:
  created:

jobs:
  initial_setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Rename Container Name
        run: |
          # Extract the repository name from GITHUB_REPOSITORY
          REPO_NAME=$(echo "${GITHUB_REPOSITORY##*/}")

          # Replace {REPO_NAME} in docker-compose.yml
          sed -i "s/{REPO_NAME}/${REPO_NAME}/g" .devcontainer/docker/docker-compose.yml

      - name: Rename Folder Name
        run: |
          # Extract the repository name from GITHUB_REPOSITORY
          REPO_NAME=$(echo "${GITHUB_REPOSITORY##*/}")
          
          # Define the target folder path and the new name
          TARGET_FOLDER=".devcontainer/docker"
          NEW_FOLDER=".devcontainer/${REPO_NAME}"
          
          # Rename if the target folder exists
          if [ -d "$TARGET_FOLDER" ]; then
            mv "$TARGET_FOLDER" "$NEW_FOLDER"
            echo "Renamed $TARGET_FOLDER to $NEW_FOLDER"
          else
            echo "Folder $TARGET_FOLDER does not exist, skipping rename."
          fi

      - name: Remove initial setup workflow
        run: rm -rf .github
        continue-on-error: true

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Rename .devcontainer/docker and remove first-run workflow after initialization"
          git push
        if: success()
